-- Create cycle_snapshots table
CREATE TABLE IF NOT EXISTS cycle_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index on created_at for faster queries
CREATE INDEX IF NOT EXISTS idx_cycle_snapshots_created_at ON cycle_snapshots(created_at DESC);

-- Enable Row Level Security
ALTER TABLE cycle_snapshots ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (safe for re-running)
DROP POLICY IF EXISTS "Allow public read access" ON cycle_snapshots;
DROP POLICY IF EXISTS "Allow service role insert" ON cycle_snapshots;
DROP POLICY IF EXISTS "Allow anon insert" ON cycle_snapshots;

-- Allow public read access (for UI frontend)
CREATE POLICY "Allow public read access" ON cycle_snapshots
  FOR SELECT
  TO public
  USING (true);

-- Allow anon to insert (for backend API)
CREATE POLICY "Allow anon insert" ON cycle_snapshots
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- Allow service role to insert (for backend with service role key)
CREATE POLICY "Allow service role insert" ON cycle_snapshots
  FOR INSERT
  TO service_role
  WITH CHECK (true);
